### PR TITLE
feat: created context and updated the counter only

### PR DESCRIPTION
**Pull request by ajit-sharmaGH**

### CODE REVIEW

**Comment by ajit-sharmaGH** [comment]
- navbar
image
- sidebar
image

**Review by JantuDeb — APPROVED** [review]
This is looking good you can merge

**Comment by ozairkhan2810** [comment]
If item is already there in wishlist, it is still increasing counter. Other than this looks good

**Review by ozairkhan2810 — APPROVED** [review]

**Review by anshikaa12 — APPROVED** [review]
code looks good to merge
it is clean and well structured
readable!

**Pull request merged**
